name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: wget https://github.com/camthesaxman/qemu-irix/releases/download/v0.1/qemu-irix && export QEMU_IRIX = ./qemu-irix
    - name: make
      run: make
